### ISSUE TITLE
Errors in ethereum-shkeeper pod

### ISSUE THREAD

**Issue by sajphon** [vsys-host/ethereum-shkeeper#1]
Hello, i'm getting recurring error  when i take a peek at the pod logs. What can i do about this ?

All pods are running correctly, eth chain is 100% synced, state is still syncing @ 29%.

```
[2023-05-15 02:37:51,346] ERROR: Exception in main block scanner loop: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/app/app/events.py", line 102, in events_listener
    last_checked_block = int(pd.value)
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by yukonet** [comment]
Hello,

Try running the ethereum-shkeeper pod with the LAST_BLOCK_LOCKED = "False" environment variable.
After the ethereum-shkeeper pod writes the last block number to the database, you can remove LAST_BLOCK_LOCKED from the environment variables.

**Comment by sajphon** [comment]
I will try and report back. Thank you 👍

**Comment by sajphon** [comment]
It worked, thank you <3
